"""Initial migration

Revision ID: b3de2b319cfb
Revises: 
Create Date: 2024-07-14 21:06:27.225783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3de2b319cfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('sns_type', sa.Enum('KAKAO', 'GOOGLE', name='snstype'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activitylevelenum'), nullable=True),
    sa.Column('daily_calorie_goal', sa.Integer(), nullable=True),
    sa.Column('daily_protein_goal', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('daily_fat_goal', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('daily_carb_goal', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_time', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', 'late_night', name='mealtypeenum'), nullable=False),
    sa.Column('calories', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('protein', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('fat', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('carbs', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_records_id'), 'meal_records', ['id'], unique=False)
    op.alter_column('tests', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'description',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_meal_records_id'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
